"""
Interactive field mapper

Provides an interactive UI for manually mapping source fields to target fields.
"""

from typing import List, Optional, Dict, Any
from rich.table import Table
from rich.prompt import Prompt, Confirm
from rich.panel import Panel
from core.models import FieldMapping
from ..banner import console


class InteractiveMapper:
    """
    Interactive field mapping with Rich UI.

    Example:
        mapper = InteractiveMapper(source_headers, sample_records)
        mapping = mapper.map()
    """

    def __init__(self, source_headers: List[str], sample_records: Optional[List[Dict[str, Any]]] = None):
        """
        Initialize interactive mapper.

        Args:
            source_headers: List of source column names
            sample_records: Optional list of sample records for preview (recommended 3-5 records)
        """
        self.source_headers = source_headers
        self.sample_records = sample_records or []

    def map(self, auto_mapping: Optional[FieldMapping] = None) -> FieldMapping:
        """
        Interactively map fields.

        Args:
            auto_mapping: Optional pre-detected mapping to use as defaults

        Returns:
            FieldMapping with user-selected mappings
        """
        # Clean header
        console.print()
        console.rule("[bold cyan]◎ Field Mapping[/bold cyan]", style="cyan")
        console.print("[dim]Map your source columns → standard export format[/dim]")

        # Show quick tips
        self._show_quick_tips()

        # Show available source columns
        console.print()
        self._show_source_columns()

        # If auto-mapping provided, ask if user wants to review/modify
        if auto_mapping and auto_mapping.is_complete():
            console.print()
            console.print("[green]✦ Auto-mapping detected all required fields![/green]")
            self._show_auto_mapping(auto_mapping)

            if Confirm.ask("\n[cyan]Use auto-detected mapping?[/cyan]", default=True):
                console.print("[green]☉ Auto-mapping accepted[/green]")
                return auto_mapping

            console.print("\n[yellow]⚙  Manual mapping mode enabled[/yellow]")

        # Manual mapping
        mapping = FieldMapping()

        # Required fields (skippable — enrichment can fill them later)
        console.print()
        console.rule("[bold cyan]Required Fields[/bold cyan] [dim](2 fields)[/dim]", style="cyan")
        console.print("[dim]Recommended — skip if Exa will generate them later[/dim]\n")

        mapping.domain = self._map_field(
            "Domain",
            "Company website domain (skip → Exa resolves from company name)",
            "acme.com (without http://)",
            auto_mapping.domain if auto_mapping else None,
            required=False,
            step="1/2"
        )
        mapping.company_description = self._map_field(
            "Context",
            "Company description (skip → Exa generates from domain)",
            "About the company, industry, etc.",
            auto_mapping.company_description if auto_mapping else None,
            required=False,
            step="2/2"
        )

        # Optional fields
        console.print()
        console.rule("[bold yellow]Optional Fields[/bold yellow] [dim](4 fields)[/dim]", style="yellow")
        console.print("[dim]Press Enter to skip — signal can be generated by Exa later[/dim]\n")

        mapping.signal = self._map_field(
            "Signal",
            "WHY NOW trigger — the reason for outreach (skip if using Exa)",
            "Hiring: VP of Sales, Raised $5M Series A, etc.",
            auto_mapping.signal if auto_mapping else None,
            required=False,
            step="1/4"
        )
        mapping.full_name = self._map_field(
            "Full Name",
            "Contact's full name",
            "John Doe, Sarah Smith, etc.",
            auto_mapping.full_name if auto_mapping else None,
            required=False,
            step="2/4"
        )
        mapping.company_name = self._map_field(
            "Company Name",
            "Company or organization",
            "Acme Corp, Tech Inc, etc.",
            auto_mapping.company_name if auto_mapping else None,
            required=False,
            step="3/4"
        )
        mapping.email = self._map_field(
            "Email",
            "Contact email address",
            "john@acme.com",
            auto_mapping.email if auto_mapping else None,
            required=False,
            step="4/4"
        )

        # Show final mapping summary
        console.print()
        console.rule("[bold green]✦ Mapping Complete![/bold green]", style="green")
        self._show_mapping_summary(mapping)

        return mapping

    def _show_quick_tips(self):
        """Show helpful tips for fast mapping."""
        tips_panel = Panel(
            "[bold]Quick Tips:[/bold]\n"
            "  • Type column [cyan]number[/cyan] (e.g., '1') or [cyan]name[/cyan] (e.g., 'email')\n"
            "  • Press [green]Enter[/green] to use auto-detected value\n"
            "  • Press [green]Enter[/green] to skip optional fields\n"
            "  • Type partial names for fuzzy match (e.g., 'comp' → 'company')",
            title="[bold cyan]☾ How to Map[/bold cyan]",
            border_style="blue",
            padding=(0, 1),
            expand=False
        )
        console.print(tips_panel)

    def _show_source_columns(self):
        """Display available source columns with sample data."""
        if self.sample_records:
            table = Table(title="Available Source Columns (with sample data)", show_header=True)
            table.add_column("#", style="dim", width=4)
            table.add_column("Column Name", style="cyan bold", width=25)
            table.add_column("Sample Values", style="white", overflow="fold")

            for i, header in enumerate(self.source_headers, 1):
                # Get sample values from first 3 records
                samples = []
                for record in self.sample_records[:3]:
                    val = record.get(header, "")
                    if val:
                        val_str = str(val)[:40]  # Truncate long values
                        if len(str(val)) > 40:
                            val_str += "..."
                        samples.append(val_str)

                sample_text = " | ".join(samples) if samples else "[dim]<empty>[/dim]"
                table.add_row(f"{i}.", header, sample_text)
        else:
            # Fallback to simple table if no sample data
            table = Table(title="Available Source Columns", show_header=False)
            table.add_column("Index", style="dim", width=6)
            table.add_column("Column Name", style="cyan")

            for i, header in enumerate(self.source_headers, 1):
                table.add_row(f"{i}.", header)

        console.print(table)

    def _show_auto_mapping(self, mapping: FieldMapping):
        """Display auto-detected mapping."""
        table = Table(title="Auto-Detected Mapping")
        table.add_column("Target Field", style="cyan")
        table.add_column("Source Column", style="green")

        summary = {}
        for field in vars(mapping):
            source = getattr(mapping, field)
            if source is not None:
                summary[field] = source

        for target, source in summary.items():
            table.add_row(target, source)

        console.print(table)

    def _show_mapping_summary(self, mapping: FieldMapping):
        """Display final mapping summary with stats."""
        table = Table(
            title="[bold cyan]≡ Final Mapping Summary[/bold cyan]",
            show_header=True,
            header_style="bold cyan",
            border_style="cyan",
            pad_edge=False,
            expand=False
        )
        table.add_column("Target Field", style="cyan bold", width=20)
        table.add_column("Source Column", style="white", width=25)
        table.add_column("Status", justify="center", width=20)

        mapped_count = 0
        required_count = 0
        required_fields = ['domain', 'company_name']

        for field in vars(mapping):
            source = getattr(mapping, field)
            field_display = field.replace('_', ' ').title()

            if source is not None:
                status = "[green]☉ Mapped[/green]"
                mapped_count += 1
                if field in required_fields:
                    required_count += 1
            elif field in required_fields:
                status = "[red]☿ Missing[/red]"
            else:
                status = "[dim]◯ Skipped[/dim]"

            # Add emoji for field type
            if field in required_fields:
                field_display = f"◆ {field_display}"
            else:
                field_display = f"  {field_display}"

            table.add_row(field_display, source or "-", status)

        console.print(table)

        # Show mapping quality stats
        console.print()
        quality_percentage = (required_count / len(required_fields)) * 100

        if quality_percentage == 100:
            console.print(f"[bold green]✦ Perfect![/bold green] Both required fields mapped ({required_count}/2)")
        elif quality_percentage >= 50:
            console.print(f"[yellow]▲  Partial:[/yellow] {required_count}/2 required fields mapped — Exa can fill the rest")
        else:
            console.print(f"[red]☿ Incomplete:[/red] Need at least domain or company name to proceed")

        console.print(f"[dim]Total: {mapped_count} fields mapped[/dim]")

    def _show_column_preview(self, column_name: str, field_name: str):
        """
        Show preview of what data will be mapped from this column.

        Args:
            column_name: Source column to preview
            field_name: Target field name for context
        """
        if not self.sample_records:
            return

        # Get sample values and check quality
        samples = []
        empty_count = 0
        for record in self.sample_records[:5]:  # Show up to 5 samples
            val = record.get(column_name, "")
            if val:
                val_str = str(val)[:60]  # Truncate if too long
                if len(str(val)) > 60:
                    val_str += "..."
                samples.append(val_str)
            else:
                empty_count += 1

        if not samples:
            console.print(f"[yellow]▲  Warning:[/yellow] Column '[white]{column_name}[/white]' has no data in samples")
            return

        # Build preview with quality indicator
        preview_lines = []
        for i, sample in enumerate(samples, 1):
            preview_lines.append(f"  {i}. {sample}")

        # Add quality info
        fill_rate = len(samples) / min(5, len(self.sample_records)) * 100
        if fill_rate == 100:
            quality = "[green]☉ Perfect (100% filled)[/green]"
        elif fill_rate >= 80:
            quality = f"[green]☉ Good ({fill_rate:.0f}% filled)[/green]"
        elif fill_rate >= 50:
            quality = f"[yellow]▲ Fair ({fill_rate:.0f}% filled)[/yellow]"
        else:
            quality = f"[red]☿ Poor ({fill_rate:.0f}% filled)[/red]"

        preview_text = "\n".join(preview_lines)
        preview_text += f"\n\n  {quality}"

        # Show impressive preview panel
        panel = Panel(
            preview_text,
            title=f"[bold cyan]≡ Preview: [white]{column_name}[/white] → [white]{field_name}[/white][/bold cyan]",
            border_style="green",
            padding=(0, 1),
            expand=False
        )
        console.print(panel)

    def _map_field(
        self,
        field_name: str,
        description: str,
        example: str,
        default: Optional[str] = None,
        required: bool = True,
        step: str = ""
    ) -> Optional[str]:
        """
        Map a single field interactively with beautiful UI.

        Args:
            field_name: Display name of target field
            description: Help text
            example: Example values to show
            default: Default source column (from auto-mapping)
            required: Whether field is required
            step: Progress indicator (e.g., "1/4")

        Returns:
            Selected source column name or None
        """
        # Clean header for this field
        console.print()
        if step:
            header = f"[bold cyan]{field_name}[/bold cyan] [dim]({step})[/dim]"
        else:
            header = f"[bold cyan]{field_name}[/bold cyan]"

        console.print(header)
        console.print(f"[dim]{description}[/dim]")
        console.print(f"[dim]Example: {example}[/dim]")

        # Show default if available
        if default:
            console.print(f"[green]☉ Auto-detected:[/green] [white]{default}[/white]")

        # Build helpful prompt
        if default:
            prompt_msg = "[cyan]→[/cyan] Press Enter to use auto-detected, or type column # / name"
        elif not required:
            prompt_msg = "[cyan]→[/cyan] Type column # or name (Enter to skip)"
        else:
            prompt_msg = "[cyan]→[/cyan] Type column # or name"

        console.print()

        while True:
            user_input = Prompt.ask(
                prompt_msg,
                default=default or ("" if not required else None),
                show_default=False
            )

            # Skip if empty and optional
            if not user_input and not required:
                console.print("[dim]◯ Skipped[/dim]")
                return None

            # Guard against None/empty on required fields
            if not user_input:
                console.print("[red]☿ This field is required[/red]")
                console.print("[dim]Type a column number or name...[/dim]")
                continue

            # Check if input is a number (index)
            if user_input.isdigit():
                index = int(user_input) - 1
                if 0 <= index < len(self.source_headers):
                    selected = self.source_headers[index]
                    console.print(f"[green]☉ Selected:[/green] [white]{selected}[/white]")
                    # Show preview of what data will be mapped
                    self._show_column_preview(selected, field_name)
                    return selected
                else:
                    console.print(f"[red]☿ Invalid:[/red] Index must be 1-{len(self.source_headers)}")
                    console.print("[dim]Try again...[/dim]")
                    continue

            # Check if input matches a column name
            if user_input in self.source_headers:
                console.print(f"[green]☉ Selected:[/green] [white]{user_input}[/white]")
                # Show preview of what data will be mapped
                self._show_column_preview(user_input, field_name)
                return user_input

            # Find similar matches (fuzzy search)
            matches = [h for h in self.source_headers if user_input.lower() in h.lower()]
            if len(matches) == 1:
                # Auto-select if only one match
                console.print(f"[green]☉ Matched:[/green] [white]{matches[0]}[/white]")
                self._show_column_preview(matches[0], field_name)
                return matches[0]
            elif matches:
                console.print(f"[yellow]☾ Did you mean:[/yellow] {', '.join(matches[:5])}")
                console.print("[dim]Type the exact name or number...[/dim]")
            else:
                console.print(f"[red]☿ Not found:[/red] '{user_input}'")
                console.print(f"[dim]Available columns: {', '.join(self.source_headers[:5])}{'...' if len(self.source_headers) > 5 else ''}[/dim]")
